site_name: "Site"
site_description: "Отчет для задния 2.2"
site_author: "Лежанков Максим"

theme:
  name: null
  custom_dir: custom

nav:
  - Главная: index.md
  - Документация MkDocs: documentation.md