name: Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install mkdocs mkdocs-minify-plugin

      - name: Build MkDocs site
        run: mkdocs build

      - name: Upload site as artifact
        uses: actions/upload-artifact@v4
        with:
          name: mkdocs-site
          path: site/

  test:
    name: Test Site
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: mkdocs-site
          path: site/

      - name: Install frontend tools
        run: npm install -D html-validate

      - name: Validate HTML
        run: npx html-validate "site/**/*.html"

  deploy:
    name: Deploy Site
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: mkdocs-site
          path: site/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
